In [3]:
print("Testing code")

Testing code


In [4]:
!nvidia-smi

Mon Feb 17 20:21:24 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 572.42                 Driver Version: 572.42         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   51C    P8              5W /  116W |    1191MiB /   6141MiB |      3%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu126


In [6]:
# intro to tensor

# sclaer
scaler = torch.tensor(7)
scaler

tensor(7)

In [7]:
# checking the dimention
scaler.ndim

0

In [8]:
# get tensor back as Pyhton int
scaler.item()

7

In [9]:
# vector 
vector = torch.tensor([7,7])
vector
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[4,1,2]],
                       [[5,4,6],[7,8,3],[5,3,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [4, 1, 2]],

        [[5, 4, 6],
         [7, 8, 3],
         [5, 3, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([2, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [4, 1, 2]])

In [19]:
# Random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1206, 0.7613, 0.1568, 0.6630],
        [0.1965, 0.8517, 0.9986, 0.3432],
        [0.4861, 0.9823, 0.3636, 0.2964]])